/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/upload-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Session */
        post: operations["create_upload_session_api_v1_artifacts_upload_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/upload-sessions/{session_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Artifact */
        post: operations["commit_artifact_api_v1_artifacts_upload_sessions__session_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Artifact Alias */
        post: operations["set_artifact_alias_api_v1_artifacts__artifact_id__aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Latest */
        post: operations["query_latest_api_v1_query_latest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Metrics */
        post: operations["query_metrics_api_v1_query_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/sql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Sql
         * @description Arbitrary DuckDB SQL over the org's own data (views: runs, metrics,
         *     logs) — isolation by construction in the sqlbox, never by WHERE clause.
         */
        post: operations["query_sql_api_v1_query_sql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Batch */
        post: operations["ingest_batch_api_v1_runs__run_id__batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Run */
        post: operations["finish_run_api_v1_runs__run_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Lineage */
        get: operations["get_run_lineage_api_v1_runs__run_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Logs */
        get: operations["run_logs_api_v1_runs__run_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasIn */
        AliasIn: {
            /** Alias */
            alias: string;
        };
        /** ArtifactFileOut */
        ArtifactFileOut: {
            /** Download Url */
            download_url: string;
            /** Logical Path */
            logical_path: string;
            /** Media Type */
            media_type: string | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * ArtifactKind
         * @enum {string}
         */
        ArtifactKind: "model" | "dataset" | "media" | "file";
        /** ArtifactVersionOut */
        ArtifactVersionOut: {
            /** Collection */
            collection: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Run Id */
            created_by_run_id: string | null;
            /** Digest */
            digest: string;
            /** Files */
            files: components["schemas"]["ArtifactFileOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
        };
        /** BatchAck */
        BatchAck: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Replayed */
            replayed: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** CommitArtifactIn */
        CommitArtifactIn: {
            /** Collection */
            collection: string;
            /** @default file */
            kind: components["schemas"]["ArtifactKind"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Project */
            project: string;
            /**
             * Relation
             * @default output
             */
            relation: string;
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * CreateRunIn
         * @description Create-or-attach: rank 0 and rank>0 workers, first attempts and resumes
         *     all send the same shape.
         */
        CreateRunIn: {
            /** Commit Sha */
            commit_sha?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Display Name */
            display_name?: string | null;
            /** Group Name */
            group_name?: string | null;
            /** Job Type */
            job_type?: string | null;
            /** Name */
            name: string;
            /** Project */
            project: string;
            /**
             * Resume
             * @default false
             */
            resume: boolean;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            worker: components["schemas"]["WorkerIn"];
        };
        /** CreateUploadSessionIn */
        CreateUploadSessionIn: {
            /** Files */
            files: components["schemas"]["UploadFileIn"][];
        };
        /** FinishRunIn */
        FinishRunIn: {
            /** @default completed */
            state: components["schemas"]["RunState"];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Ok */
            ok: boolean;
        };
        /** LatestMetricOut */
        LatestMetricOut: {
            /** Metric Name */
            metric_name: string;
            /** Run Id */
            run_id: string;
            /** Step */
            step: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Value */
            value: number;
        };
        /** LogLineOut */
        LogLineOut: {
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Source */
            source: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** MetricSeriesOut */
        MetricSeriesOut: {
            /** Metric Name */
            metric_name: string;
            /** Points */
            points: components["schemas"]["SeriesPointOut"][];
            /** Run Id */
            run_id: string;
        };
        /** MetricsQueryIn */
        MetricsQueryIn: {
            /**
             * Max Points
             * @default 1500
             */
            max_points: number;
            /** Metric Names */
            metric_names?: string[];
            /** Run Ids */
            run_ids: string[];
            /** Step Max */
            step_max?: number | null;
            /** Step Min */
            step_min?: number | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Name */
            name: string;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /** Commit Sha */
            commit_sha: string | null;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Group Name */
            group_name: string | null;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Job Type */
            job_type: string | null;
            /** Name */
            name: string;
            /** Project */
            project: string;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            state: components["schemas"]["RunState"];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Workers */
            workers: components["schemas"]["WorkerOut"][];
        };
        /** RunLineageOut */
        RunLineageOut: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Collection */
            collection: string;
            /** Relation */
            relation: string;
            /** Run Id */
            run_id: string;
            /** Version */
            version: number;
        };
        /** RunOut */
        RunOut: {
            /** Commit Sha */
            commit_sha: string | null;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Group Name */
            group_name: string | null;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Job Type */
            job_type: string | null;
            /** Name */
            name: string;
            /** Project */
            project: string;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            state: components["schemas"]["RunState"];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** RunRef */
        RunRef: {
            /** Org Slug */
            org_slug: string;
            /** Project */
            project: string;
            /** Run Id */
            run_id: string;
            /** Url */
            url: string;
        };
        /**
         * RunState
         * @description Byte-equal to the SDK's ``runs.status`` vocabulary (waddle/_run.py).
         * @enum {string}
         */
        RunState: "running" | "completed" | "failed" | "aborted";
        /** SeriesPointOut */
        SeriesPointOut: {
            /** Step */
            step: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Value */
            value: number;
            /** Value Max */
            value_max: number;
            /** Value Min */
            value_min: number;
        };
        /** SqlQueryIn */
        SqlQueryIn: {
            /**
             * Max Rows
             * @default 1000
             */
            max_rows: number;
            /** Sql */
            sql: string;
        };
        /** SqlResultOut */
        SqlResultOut: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: unknown[][];
            /** Truncated */
            truncated: boolean;
        };
        /** UploadFileIn */
        UploadFileIn: {
            /** Logical Path */
            logical_path: string;
            /** Media Type */
            media_type?: string | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** UploadSessionOut */
        UploadSessionOut: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Targets */
            targets: components["schemas"]["UploadTargetOut"][];
        };
        /** UploadTargetOut */
        UploadTargetOut: {
            /** Logical Path */
            logical_path: string;
            /** Sha256 */
            sha256: string;
            /** Url */
            url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerIn */
        WorkerIn: {
            /** Attempt */
            attempt: number;
            /** Local Rank */
            local_rank: number;
            /** Node Id */
            node_id: string;
            /** Rank */
            rank: number;
            /** World Size */
            world_size: number;
            /**
             * Writer Id
             * Format: uuid
             */
            writer_id: string;
        };
        /** WorkerOut */
        WorkerOut: {
            /** Attempt */
            attempt: number;
            /** Local Rank */
            local_rank: number;
            /** Node Id */
            node_id: string;
            /** Rank */
            rank: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** World Size */
            world_size: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_api_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    create_upload_session_api_v1_artifacts_upload_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_artifact_api_v1_artifacts_upload_sessions__session_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitArtifactIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_artifact_alias_api_v1_artifacts__artifact_id__aliases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AliasIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    query_latest_api_v1_query_latest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricsQueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestMetricOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_metrics_api_v1_query_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricsQueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSeriesOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_sql_api_v1_query_sql_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SqlQueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SqlResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                project?: string | null;
                state?: components["schemas"]["RunState"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_batch_api_v1_runs__run_id__batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_run_api_v1_runs__run_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_lineage_api_v1_runs__run_id__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLineageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_logs_api_v1_runs__run_id__logs_get: {
        parameters: {
            query?: {
                after_ts?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogLineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
